services:
  - type: web
    name: game123
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start -w server
    envVars:
      - key: NODE_VERSION
        value: 22
